In [1]:
import pandas as pd

In [2]:
df = pd.read_json("daily_14.json", lines=True)

In [3]:
df

,city,time,data
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"[{'dt': 1489471200, 'temp': {'day': 286.84, 'm..."
1,"{'id': 3632308, 'name': 'Merida', 'country': '...",1489465075,"[{'dt': 1489420800, 'temp': {'day': 284.63, 'm..."
2,"{'id': 1280737, 'name': 'Lhasa', 'country': 'C...",1489465075,"[{'dt': 1489471200, 'temp': {'day': 273.27, 'm..."
3,"{'id': 745042, 'name': 'İstanbul', 'country': ...",1489465075,"[{'dt': 1489399200, 'temp': {'day': 280.63, 'm..."
4,"{'id': 3496831, 'name': 'Mao', 'country': 'DO'...",1489465075,"[{'dt': 1489420800, 'temp': {'day': 296.15, 'm..."
...,...,...,...
22630,"{'id': 8199378, 'name': 'Modiin Ilit', 'countr...",1489466267,"[{'dt': 1489482000, 'temp': {'day': 290.65, 'm..."
22631,"{'id': 8199394, 'name': 'Ariel', 'country': 'I...",1489466267,"[{'dt': 1489482000, 'temp': {'day': 290.65, 'm..."
22632,"{'id': 8260318, 'name': 'Shanjeev Home', 'coun...",1489466267,"[{'dt': 1489471200, 'temp': {'day': 301.07, 'm..."
22633,"{'id': 8224933, 'name': 'PAJOK Pogee,', 'count...",1489466267,"[{'dt': 1489482000, 'temp': {'day': 307.83, 'm..."
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"[{'dt': 1489399200, 'temp': {'day': 309.48, 'm..."

In [4]:
df["city"].iloc[0]

{'id': 1283240,
 'name': 'Kathmandu',
 'country': 'NP',
 'coord': {'lon': 85.316666, 'lat': 27.716667}}

In [5]:
df["data"].iloc[0]

[{'dt': 1489471200,
  'temp': {'day': 286.84,
   'min': 269.81,
   'max': 286.84,
   'night': 269.81,
   'eve': 278.25,
   'morn': 286.15},
  'pressure': 708.98,
  'humidity': 65,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.4,
  'deg': 212,
  'clouds': 8,
  'rain': 0.96,
  'snow': 0.2,
  'uvi': 8.37},
 {'dt': 1489557600,
  'temp': {'day': 278.34,
   'min': 270.01,
   'max': 279.27,
   'night': 271.76,
   'eve': 276.5,
   'morn': 270.01},
  'pressure': 709.79,
  'humidity': 58,
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'sky is clear',
    'icon': '01d'}],
  'speed': 0.29,
  'deg': 193,
  'clouds': 0,
  'snow': 0,
  'uvi': 8.33},
 {'dt': 1489644000,
  'temp': {'day': 278.23,
   'min': 270.22,
   'max': 278.23,
   'night': 272.41,
   'eve': 274.27,
   'morn': 270.22},
  'pressure': 707.85,
  'humidity': 57,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.53,
  'deg': 179,
  'clouds': 36,
  'rain': 2.59,
  'snow': 1.01,
  'uvi': 8.69},
 {'dt': 1489730400,
  'temp': {'day': 283.83,
   'min': 276.06,
   'max': 283.83,
   'night': 276.06,
   'eve': 279.1,
   'morn': 276.38},
  'pressure': 787.6,
  'humidity': 0,
  'weather': [{'id': 601,
    'main': 'Snow',
    'description': 'snow',
    'icon': '13d'}],
  'speed': 0.8300000000000001,
  'deg': 215,
  'clouds': 17,
  'rain': 9.8,
  'snow': 4.18,
  'uvi': 7.68},
 {'dt': 1489816800,
  'temp': {'day': 283.37,
   'min': 272.76,
   'max': 283.37,
   'night': 276.06,
   'eve': 280.5,
   'morn': 272.76},
  'pressure': 788.48,
  'humidity': 0,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.74,
  'deg': 201,
  'clouds': 17,
  'rain': 2.2,
  'snow': 1.35,
  'uvi': 7.49},
 {'dt': 1489903200,
  'temp': {'day': 284.95,
   'min': 274.89,
   'max': 284.95,
   'night': 274.95,
   'eve': 281.87,
   'morn': 274.89},
  'pressure': 790,
  'humidity': 0,
  'weather': [{'id': 601,
    'main': 'Snow',
    'description': 'snow',
    'icon': '13d'}],
  'speed': 0.6900000000000001,
  'deg': 205,
  'clouds': 41,
  'rain': 2.05,
  'snow': 2.05,
  'uvi': 8.3},
 {'dt': 1489989600,
  'temp': {'day': 283.35,
   'min': 272.73,
   'max': 283.35,
   'night': 273.35,
   'eve': 281.32,
   'morn': 272.73},
  'pressure': 790.08,
  'humidity': 0,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.85,
  'deg': 240,
  'clouds': 26,
  'rain': 1.97,
  'snow': 1.35,
  'uvi': 9.3},
 {'dt': 1490076000,
  'temp': {'day': 287.06,
   'min': 271.35,
   'max': 287.06,
   'night': 274.74,
   'eve': 285.12,
   'morn': 271.35},
  'pressure': 790.94,
  'humidity': 0,
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'sky is clear',
    'icon': '01d'}],
  'speed': 0.5,
  'deg': 291,
  'clouds': 0,
  'uvi': 9.3},
 {'dt': 1490162400,
  'temp': {'day': 287.84,
   'min': 273.87,
   'max': 287.84,
   'night': 276.31,
   'eve': 286.25,
   'morn': 273.87},
  'pressure': 790.56,
  'humidity': 0,
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'sky is clear',
    'icon': '01d'}],
  'speed': 0.65,
  'deg': 262,
  'clouds': 0,
  'snow': 0.01,
  'uvi': 9.3},
 {'dt': 1490248800,
  'temp': {'day': 289.08,
   'min': 273.25,
   'max': 289.08,
   'night': 278.02,
   'eve': 288.06,
   'morn': 273.25},
  'pressure': 789.54,
  'humidity': 0,
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'speed': 0.58,
  'deg': 271,
  'clouds': 0,
  'rain': 0.2,
  'uvi': 9.3},
 {'dt': 1490335200,
  'temp': {'day': 290.51,
   'min': 276,
   'max': 290.51,
   'night': 279.46,
   'eve': 288.44,
   'morn': 276},
  'pressure': 790.5,
  'humidity': 0,
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'speed': 0.6000000000000001,
  'deg': 251,
  'clouds': 0,
  'rain': 0.31,
  'uvi': 9.3},
 {'dt': 1490421600,
  'temp': {'day': 290.91,
   'min': 277.51,
   'max': 290.91,
   'night': 278.02,
   'eve': 287.6,
   'morn': 277.51},
  'pressure': 790.91,
  'humidity': 0,
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'sky is clear',
    'icon': '01d'}],
  'speed': 0.72,
  'deg': 262,
  'clouds': 1,
  'snow': 0.03,
  'uvi': 9.3},
 {'dt': 1490508000,
  'temp': {'day': 290.32,
   'min': 278.79,
   'max': 290.32,
   'night': 281.03,
   'eve': 287.87,
   'morn': 278.79},
  'pressure': 790.04,
  'humidity': 0,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.63,
  'deg': 148,
  'clouds': 28,
  'snow': 0.11,
  'uvi': 9.3},
 {'dt': 1490594400,
  'temp': {'day': 288.95,
   'min': 279.25,
   'max': 288.95,
   'night': 280.36,
   'eve': 284.65,
   'morn': 279.25},
  'pressure': 791.55,
  'humidity': 0,
  'weather': [{'id': 600,
    'main': 'Snow',
    'description': 'light snow',
    'icon': '13d'}],
  'speed': 0.6000000000000001,
  'deg': 168,
  'clouds': 67,
  'rain': 3.66,
  'snow': 1.25,
  'uvi': 9.3},
 {'dt': 1490680800,
  'temp': {'day': 285.5,
   'min': 278.1,
   'max': 285.5,
   'night': 278.1,
   'eve': 281.73,
   'morn': 279.04},
  'pressure': 792.56,
  'humidity': 0,
  'weather': [{'id': 601,
    'main': 'Snow',
    'description': 'snow',
    'icon': '13d'}],
  'speed': 0.8200000000000001,
  'deg': 186,
  'clouds': 42,
  'rain': 8.4,
  'snow': 1.8900000000000001,
  'uvi': 9.3},
 {'dt': 1490767200,
  'temp': {'day': 274.7,
   'min': 274.7,
   'max': 274.7,
   'night': 274.7,
   'eve': 274.7,
   'morn': 274.7},
  'pressure': 789.81,
  'humidity': 0,
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'sky is clear',
    'icon': '01d'}],
  'speed': 0.78,
  'deg': 43,
  'clouds': 8,
  'snow': 0.01,
  'uvi': 9.3}]

In [ ]:
1. How many city records are in the file?
2. How many unique countries are represented?
3. Which 10 countries have the most cities in this file?
4. Explode each city’s daily forecast array into one row per (city, country, date). How many total rows?
5. For each city, use the mean of temp.day across its forecast horizon and list the top 10 hottest cities.
6. Build a tidy table for San Francisco, California.
Include columns: date, temp_min, temp_max, humidity, weather_description.
Convert temperatures from Kelvin to °C.
Format the dates to be human readable, e.g.: YYYY‑MM‑DD

# 1. How many city records are in the file?

In [8]:
city_df = pd.json_normalize(df["city"])

In [9]:
city_df

            id           name country  coord.lon  coord.lat
0      1283240      Kathmandu      NP  85.316666  27.716667
1      3632308         Merida      VE -71.144997   8.598333
2      1280737          Lhasa      CN  91.099998  29.650000
3       745042       İstanbul      TR  28.983311  41.035080
4      3496831            Mao      DO -71.078133  19.551861
...        ...            ...     ...        ...        ...
22630  8199378    Modiin Ilit      IL  35.044159  31.932211
22631  8199394          Ariel      IL  35.184490  32.106499
22632  8260318  Shanjeev Home      LK  81.841980   7.382160
22633  8224933   PAJOK Pogee,      SS  32.517319   3.767630
22634  8224935   Magwi County      SS  32.301479   4.125320

[22635 rows x 5 columns]

In [10]:
city_df.id.nunique()

22635

In [12]:
city_df[["name", "country", "coord.lon", "coord.lat"]].duplicated().any()

np.False_

# 2. How many unique countries are represented?

In [13]:
city_df.country.nunique()

243

# 3. Which 10 countries have the most cities in this file?

In [15]:
city_df.groupby("country").id.nunique().sort_values(ascending=False).head(10)

country
US    2924
IN    2393
BR    1194
DE     985
RU     953
CN     788
JP     752
GB     672
IT     670
FR     610
Name: id, dtype: int64

In [ ]:
4. Explode each city’s daily forecast array into one row per (city, country, date). How many total rows?
5. For each city, use the mean of temp.day across its forecast horizon and list the top 10 hottest cities.
6. Build a tidy table for San Francisco, California.
Include columns: date, temp_min, temp_max, humidity, weather_description.
Convert temperatures from Kelvin to °C.
Format the dates to be human readable, e.g.: YYYY‑MM‑DD

# 4. Explode each city’s daily forecast array into one row per (city, country, date). How many total rows?

In [16]:
explode = df.explode("data")
explode

,city,time,data
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"{'dt': 1489471200, 'temp': {'day': 286.84, 'mi..."
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"{'dt': 1489557600, 'temp': {'day': 278.34, 'mi..."
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"{'dt': 1489644000, 'temp': {'day': 278.23, 'mi..."
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"{'dt': 1489730400, 'temp': {'day': 283.83, 'mi..."
0,"{'id': 1283240, 'name': 'Kathmandu', 'country'...",1489465075,"{'dt': 1489816800, 'temp': {'day': 283.37, 'mi..."
...,...,...,...
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"{'dt': 1490432400, 'temp': {'day': 304.6, 'min..."
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"{'dt': 1490518800, 'temp': {'day': 302.17, 'mi..."
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"{'dt': 1490605200, 'temp': {'day': 306, 'min':..."
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"{'dt': 1490691600, 'temp': {'day': 305.83, 'mi..."
22634,"{'id': 8224935, 'name': 'Magwi County', 'count...",1489466267,"{'dt': 1490778000, 'temp': {'day': 291.95, 'mi..."

In [17]:
data_df = pd.concat([pd.json_normalize(explode["city"]),
                     pd.json_normalize(explode["data"])],
                    axis=1)

In [18]:
data_df

,id,name,country,coord.lon,coord.lat,dt,pressure,humidity,weather,speed,...,clouds,rain,snow,uvi,temp.day,temp.min,temp.max,temp.night,temp.eve,temp.morn
0,1283240,Kathmandu,NP,85.316666,27.716667,1489471200,708.98,65,"[{'id': 600, 'main': 'Snow', 'description': 'l...",0.40,...,8,0.96,0.20,8.37,286.84,269.81,286.84,269.81,278.25,286.15
1,1283240,Kathmandu,NP,85.316666,27.716667,1489557600,709.79,58,"[{'id': 800, 'main': 'Clear', 'description': '...",0.29,...,0,NaN,0.00,8.33,278.34,270.01,279.27,271.76,276.50,270.01
2,1283240,Kathmandu,NP,85.316666,27.716667,1489644000,707.85,57,"[{'id': 600, 'main': 'Snow', 'description': 'l...",0.53,...,36,2.59,1.01,8.69,278.23,270.22,278.23,272.41,274.27,270.22
3,1283240,Kathmandu,NP,85.316666,27.716667,1489730400,787.60,0,"[{'id': 601, 'main': 'Snow', 'description': 's...",0.83,...,17,9.80,4.18,7.68,283.83,276.06,283.83,276.06,279.10,276.38
4,1283240,Kathmandu,NP,85.316666,27.716667,1489816800,788.48,0,"[{'id': 600, 'main': 'Snow', 'description': 'l...",0.74,...,17,2.20,1.35,7.49,283.37,272.76,283.37,276.06,280.50,272.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368904,8224935,Magwi County,SS,32.301479,4.125320,1490432400,924.43,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",1.32,...,26,6.44,NaN,15.17,304.60,290.89,304.60,290.89,294.12,295.11
368905,8224935,Magwi County,SS,32.301479,4.125320,1490518800,924.86,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",1.74,...,39,8.93,NaN,15.17,302.17,289.75,302.17,289.75,293.33,295.37
368906,8224935,Magwi County,SS,32.301479,4.125320,1490605200,923.59,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",1.92,...,25,2.22,NaN,15.17,306.00,290.64,306.00,290.64,295.16,295.35
368907,8224935,Magwi County,SS,32.301479,4.125320,1490691600,922.71,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",3.45,...,47,3.35,NaN,15.17,305.83,291.95,305.83,291.95,296.90,296.85
368908,8224935,Magwi County,SS,32.301479,4.125320,1490778000,925.99,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",1.58,...,11,0.52,NaN,15.17,291.95,291.95,291.95,291.95,291.95,291.95

# 5. For each city, use the mean of temp.day across its forecast horizon and list the top 10 hottest cities.

In [19]:
data_df.groupby(["id", "name", "country"])["temp.day"].mean().sort_values(ascending=False).head(10)

id       name       country
2433055  Dourbali   TD         312.233529
2331447  Maiduguri  NG         311.895294
2331528  Magumeri   NG         311.895294
2345521  Damaturu   NG         311.889412
2428228  Massakory  TD         311.836471
2447416  Ayorou     NE         311.827647
2324767  Potiskum   NG         311.765882
2345096  Daura      NG         311.765882
2233805  Bogo       CM         311.739412
2341294  Geidam     NG         311.727647
Name: temp.day, dtype: float64

# 6. Build a tidy table for San Francisco, California.
Include columns: date, temp_min, temp_max, humidity, weather_description.
Convert temperatures from Kelvin to °C.
Format the dates to be human readable, e.g.: YYYY‑MM‑DD

In [21]:
data_df[(data_df["name"]=="San Francisco")&(data_df["country"]=="US")].id.unique()

array([5391959])

In [26]:
sf_df = pd.DataFrame()
sf_df[["date", "temp_min", "temp_max", "humidity", "weather"]] = data_df[data_df.id==5391959][["dt", "temp.min","temp.max", "humidity", "weather"]]

In [28]:
sf_df.weather.iloc[0]

[{'id': 800, 'main': 'Clear', 'description': 'sky is clear', 'icon': '01n'}]

In [29]:
sf_df.weather.apply(len).unique()

array([1])

In [30]:
sf_df["weather_description"] = sf_df.weather.apply(lambda x: x[0]["description"])

In [31]:
sf_df["temp_min"]

,date,temp_min,temp_max,humidity,weather,weather_description
363367,1489435200,282.96,292.10,67,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear
363368,1489521600,280.60,299.08,55,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear
363369,1489608000,281.78,295.90,56,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear
363370,1489694400,283.33,291.90,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363371,1489780800,279.65,291.71,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363372,1489867200,282.35,289.94,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363373,1489953600,283.65,291.23,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363374,1490040000,279.97,291.50,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363375,1490126400,277.72,289.82,0,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear
363376,1490212800,277.00,289.65,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363377,1490299200,278.36,285.40,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",moderate rain
363378,1490385600,281.16,288.21,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",moderate rain
363379,1490472000,278.60,286.74,0,"[{'id': 500, 'main': 'Rain', 'description': 'l...",light rain
363380,1490558400,281.42,286.85,0,"[{'id': 501, 'main': 'Rain', 'description': 'm...",moderate rain
363381,1490644800,278.70,288.94,0,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear
363382,1490731200,277.28,292.45,0,"[{'id': 800, 'main': 'Clear', 'description': '...",sky is clear

In [32]:
sf_df["temp_min"] = sf_df["temp_min"] - 273.15
sf_df["temp_max"] = sf_df["temp_max"] - 273.15
sf_df["date"] = pd.to_datetime(sf_df["date"], unit="s").dt.strftime("%Y-%m-%d")

# Display the final tidy table
sf_df[["date", "temp_min", "temp_max", "humidity", "weather_description"]]

              date  temp_min  temp_max  humidity weather_description
363367  2017-03-13      9.81     18.95        67        sky is clear
363368  2017-03-14      7.45     25.93        55        sky is clear
363369  2017-03-15      8.63     22.75        56        sky is clear
363370  2017-03-16     10.18     18.75         0          light rain
363371  2017-03-17      6.50     18.56         0          light rain
363372  2017-03-18      9.20     16.79         0          light rain
363373  2017-03-19     10.50     18.08         0          light rain
363374  2017-03-20      6.82     18.35         0          light rain
363375  2017-03-21      4.57     16.67         0        sky is clear
363376  2017-03-22      3.85     16.50         0          light rain
363377  2017-03-23      5.21     12.25         0       moderate rain
363378  2017-03-24      8.01     15.06         0       moderate rain
363379  2017-03-25      5.45     13.59         0          light rain
363380  2017-03-26      8.27     13.70         0       moderate rain
363381  2017-03-27      5.55     15.79         0        sky is clear
363382  2017-03-28      4.13     19.30         0        sky is clear